name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document first
        uses: xu-cheng/latex-action@v3
        with:
          root_file: vs-script-first-v01.tex
          args: " -synctex=1 -file-line-error -interaction=nonstopmode"
          
      - name: Compile LaTeX document second
        uses: xu-cheng/latex-action@v3
        with:
          root_file: vs-script-first-v01.tex
          args: " -synctex=1 -file-line-error -interaction=nonstopmode"

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: vs-script-first-v01.pdf
